### ISSUE TITLE
Icon looks different than telescope link

### ISSUE THREAD

**Issue by ragingdave** [mad-web/nova-horizon-link#1]
Maybe this is just my OCD, but can either this or the telescope link be updated to match the other?

When they are placed right next to each other it's somewhat annoying.
![screen shot 2018-11-09 at 4 25 18 pm](https://user-images.githubusercontent.com/1168344/48289139-7e200b00-e43c-11e8-85a4-73e586757da8.png)

**Comment by slavarazum** [comment]
Horizon and Telescope logos made differently.
Use simple labels to make it looks the same.
