### ISSUE TITLE
Link style should me apple the global style

### ISSUE THREAD

**Issue by bolechen** [mad-web/nova-horizon-link#4]
When i use the 3rd theme package 

https://novapackages.com/packages/stephenlake/nova-snowball

The sidebar is looks different. In `navigation.blade.php` should use the `<h3>` tag wrap the a tag to apple the global style like other menus.

![image](https://user-images.githubusercontent.com/195015/56434278-82632500-6306-11e9-8cbf-8d93d8956c3f.png)

**Comment by austinheap** [comment]
Also broken in https://github.com/mad-web/nova-telescope-link
